<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Answer;
use AppBundle\Entity\Question;
use Doctrine\ORM\EntityRepository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{
    public function findForUser($userId){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $not=$qb ->select('IDENTITY(a.form)')
            ->from('AppBundle:Answer', 'a')
            ->where('a.user = :userId')
            ->groupBy('a.form')
        ;
        $qb = $em->createQueryBuilder();
        $forms = $qb->select('f')
            ->from('AppBundle:Form', 'f')
            ->where($qb->expr()->notIn('f.id', $not->getDQL()))
            ->setParameter("userId",$userId)
            ->getQuery()
            ->getResult();

        return $forms;

    }


    public function findResultFormByQuestion($id){
        $em = $this->getEntityManager();

        $questions = $em->getRepository('AppBundle:Question')->getQuestionsByForm($id);


        $qb = $em->createQueryBuilder();
        $answers=$qb ->select('a')
            ->from('AppBundle:Answer', 'a')
            ->where('a.form = :formId')
            ->setParameter('formId',$id)
            ->getQuery()
            ->getResult();
        $resultsTmp=[];
        $choices= Question::$choices;
        foreach ($questions as $numberQuestion=>$question) {
            foreach ($choices as $key=>$choice) {
                $resultsTmp[$numberQuestion][$key]=0;
            }
        }
        $totalAnswers=$this->amountUsersAnswerForm($id);
        foreach ($answers as $answer){
            $resultsTmp[$answer->getQuestion()->getId()][$answer->getAnswer()]++;
        }
        $results=[];
        foreach ($resultsTmp as $numQuestion=>$result){
            foreach ($result as $keyChoice=>$val){
                $results[$numQuestion][$keyChoice]=round($val*100/$totalAnswers,2);
            }
        }

        return $results;
    }

    public function amountUsersAnswerForm($idForm){
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        $amount = $qb->select('COUNT(a)')
            ->from('AppBundle:Answer', 'a')
            ->where('a.form = :formId')
            ->groupBy('a.user')
            ->setParameter("formId",$idForm)
            ->getQuery()
            ->getResult();
        return count($amount);
    }

}
