<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    function getQuestionsByForm($id)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        $questionsTmp = $qb->select('q.id,q.question')
            ->from('AppBundle:Question', 'q')
            ->where('q.form = :formId')
            ->setParameter("formId", $id)
            ->getQuery()
            ->getResult();
        $questions=[];
        foreach ($questionsTmp as $question){
            $questions[$question['id']]=$question['question'];
        }
        return $questions;
    }
}
