# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
      default:
        entity:
            class: AppBundle:User
            property: username

    role_hierarchy:
        ROLE_ADMINISTRATOR: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
           stateless:  false
           pattern:    ^/
           provider: default
           form_login:
               login_path: /login
               check_path: /login_check
               username_parameter: _username
           logout:
             path: /logout
             target: /login
           security: true
           anonymous: true
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
